apiVersion: v1
kind: Service
metadata:
  name: argo-test-app1
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  type: LoadBalancer
  LoadBalancerIP: 192.168.10.65
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: argo-test-app1